<?php

$PERMISSIONS = array();
$P_GROUP = array();

// 报表查看
define('REPORTER', 12);
define('REPORTER_ORDER', 0);
define('REPORTER_ORDER_STORE', 1);
define('REPORTER_STORE_REQUIRE', 2);
define('REPORTER_STORE_REQUIRE_STORE', 3);

$PERMISSIONS[REPORTER][REPORTER_ORDER] = '查看订单报表(全部)';
$PERMISSIONS[REPORTER][REPORTER_ORDER_STORE] = '查看订单报表(本门店)';
$PERMISSIONS[REPORTER][REPORTER_STORE_REQUIRE] = '查看订单需求(全部)';
$PERMISSIONS[REPORTER][REPORTER_STORE_REQUIRE_STORE] = '查看订单需求(本门店)';

$P_GROUP[REPORTER] = '报表查看';

// 角色管理
define('ROLE', 1);
define('ROLE_VIEW', 0);
define('ROLE_EDIT', 1);
define('ROLE_ADD', 2);
$PERMISSIONS[ROLE][ROLE_VIEW] = '角色查看';
$PERMISSIONS[ROLE][ROLE_EDIT] = '角色编辑';
$PERMISSIONS[ROLE][ROLE_ADD] = '角色添加';

$P_GROUP[ROLE] = '角色管理';


// 后台管理员管理
define('ADMIN', 2);
define('ADMIN_VIEW', 0);
define('ADMIN_EDIT', 1);
define('ADMIN_ADD', 2);
$PERMISSIONS[ADMIN][ROLE_VIEW] = '管理员查看';
$PERMISSIONS[ADMIN][ROLE_EDIT] = '管理员编辑';
$PERMISSIONS[ADMIN][ROLE_ADD] = '管理员添加';

$P_GROUP[ADMIN] = '后台管理员管理';

// 订单管理
define('ORDER', 3);
define('ORDER_SITE_VIEW', 0);
define('ORDER_SITE_VIEW_STORE', 10);
define('ORDER_SITE_EDIT', 1);
define('ORDER_SITE_EDIT_SUPPER', 2);

define('ORDER_ACCUMULATE_VIEW', 4);
define('ORDER_ACCUMULATE_VIEW_STORE', 11);
define('ORDER_ACCUMULATE_EDIT', 5);
define('ORDER_HOT_VIEW', 6);
define('ORDER_HOT_VIEW_STORE', 12);
define('ORDER_HOT_EDIT', 7);
define('ORDER_EXECUTE_VIEW', 8);
define('ORDER_EXECUTE_VIEW_STORE', 15);
define('ORDER_EXECUTE_EDIT', 9);
define('ORDER_HOT_ADD_RANGE_ALL', 16);
define('ORDER_HOT_ADD_RANGE_STORE', 17);
define('ORDER_SP_VIEW', 18);
define('ORDER_SP_VIEW_STORE', 19);
define('ORDER_SP_EDIT', 20);

$PERMISSIONS[ORDER][ORDER_SITE_VIEW] = '普通商城订单查看(全部)';
$PERMISSIONS[ORDER][ORDER_SITE_VIEW_STORE] = '普通商城订单查看(本门店)';
$PERMISSIONS[ORDER][ORDER_SITE_EDIT] = '普通商城订单管理(新增/废除/修改自定义下次配送信息)';
$PERMISSIONS[ORDER][ORDER_SITE_EDIT_SUPPER] = '超级权限(可强制修改应付款/已支付订单)';
$PERMISSIONS[ORDER][ORDER_ACCUMULATE_VIEW] = '积分商城订单查看(全部)';
$PERMISSIONS[ORDER][ORDER_ACCUMULATE_VIEW_STORE] = '积分商城订单查看(本门店)';
$PERMISSIONS[ORDER][ORDER_ACCUMULATE_EDIT] = '积分商城订单管理(新增)';
$PERMISSIONS[ORDER][ORDER_HOT_VIEW] = '抢购商城订单查看(全部)';
$PERMISSIONS[ORDER][ORDER_HOT_VIEW_STORE] = '抢购商城订单查看(本门店)';
$PERMISSIONS[ORDER][ORDER_HOT_EDIT] = '抢购商城订单管理(新增/修改/删除)';
$PERMISSIONS[ORDER][ORDER_HOT_ADD_RANGE_ALL] = '抢购商城订单新增范围(全部)';
$PERMISSIONS[ORDER][ORDER_HOT_ADD_RANGE_STORE] = '抢购商城订单新增范围(本门店)';
$PERMISSIONS[ORDER][ORDER_EXECUTE_VIEW] = '执行订单查看(全部)';
$PERMISSIONS[ORDER][ORDER_EXECUTE_VIEW_STORE] = '执行订单查看(本门店)';
$PERMISSIONS[ORDER][ORDER_EXECUTE_EDIT] = '执行订单管理(门店处理/用户自提)';
$PERMISSIONS[ORDER][ORDER_SP_VIEW] = '店员自处理订单查看(全部)';
$PERMISSIONS[ORDER][ORDER_SP_VIEW_STORE] = '店员自处理订单查看(本门店)';
$PERMISSIONS[ORDER][ORDER_SP_EDIT] = '店员自处理订单管理(废除)';

$P_GROUP[ORDER] = '订单管理';


// 商品管理
define('COMMODITY', 4);
define('COMMODITY_COMMON_VIEW', 2);
define('COMMODITY_COMMON_EDIT', 3);
define('COMMODITY_COMMON_SHOP_VIEW', 4);
define('COMMODITY_COMMON_SHOP_EDIT', 5);
define('COMMODITY_ACCUMULATE_SHOP_VIEW', 6);
define('COMMODITY_ACCUMULATE_SHOP_EDIT', 7);
define('COMMODITY_HOT_SHOP_VIEW', 8);
define('COMMODITY_HOT_SHOP_EDIT', 9);
define('COMMODITY_HOT_RANGE_ALL', 10);
define('COMMODITY_HOT_RANGE_STORE', 11);

$PERMISSIONS[COMMODITY][COMMODITY_COMMON_VIEW] = '基础商品查看';
$PERMISSIONS[COMMODITY][COMMODITY_COMMON_EDIT] = '基础商品管理(新增/修改/删除)';
$PERMISSIONS[COMMODITY][COMMODITY_COMMON_SHOP_VIEW] = '普通商城商品查看';
$PERMISSIONS[COMMODITY][COMMODITY_COMMON_SHOP_EDIT] = '普通商城商品管理(新增/修改/删除)';
$PERMISSIONS[COMMODITY][COMMODITY_ACCUMULATE_SHOP_VIEW] = '积分商城商品查看';
$PERMISSIONS[COMMODITY][COMMODITY_ACCUMULATE_SHOP_EDIT] = '积分商城商品管理(新增/修改/删除)';
$PERMISSIONS[COMMODITY][COMMODITY_HOT_SHOP_VIEW] = '抢购商城商品查看';
$PERMISSIONS[COMMODITY][COMMODITY_HOT_SHOP_EDIT] = '抢购商城商品管理(新增/修改/删除)';
$PERMISSIONS[COMMODITY][COMMODITY_HOT_RANGE_ALL] = '抢购商品上架范围选择(全部)';
$PERMISSIONS[COMMODITY][COMMODITY_HOT_RANGE_STORE] = '抢购商品上架范围选择(本门店)';

$P_GROUP[COMMODITY] = '商品管理';


// 采购管理
define('PURCHASE', 5);
define('PURCHASE_VIEW', 0);
define('PURCHASE_EDIT', 1);
define('PURCHASE_REVIEW', 2);
define('PURCHASE_LACK_VIEW', 3);
define('CLASS_VIEW', 4);
define('CLASS_EDIT', 5);
define('CLASS_SUPPLIER', 6);
define('PURCHASE_LACK_VIEW_STORE', 7);

$PERMISSIONS[PURCHASE][PURCHASE_LACK_VIEW] = '品类缺货情况查看(全部)';
$PERMISSIONS[PURCHASE][PURCHASE_LACK_VIEW_STORE] = '品类缺货情况查看(本门店)';
$PERMISSIONS[PURCHASE][CLASS_VIEW] = '品类查看';
$PERMISSIONS[PURCHASE][CLASS_SUPPLIER] = '品类供应商管理(查看/新增/修改)';
$PERMISSIONS[PURCHASE][CLASS_EDIT] = '品类管理(品类新增/修改/删除)';
$PERMISSIONS[PURCHASE][PURCHASE_VIEW] = '采购单查看';
$PERMISSIONS[PURCHASE][PURCHASE_EDIT] = '采购单废弃(只能废除自己、且尚未被审核的采购单)';
$PERMISSIONS[PURCHASE][PURCHASE_REVIEW] = '采购单审核';

$P_GROUP[PURCHASE] = '采购管理';


// 财务管理
define('FINANCE', 6);
define('FINANCE_VIEW', 0);
define('FINANCE_EDIT', 1);
define('FINANCE_PURCHASE_REVIEW', 2);

$PERMISSIONS[FINANCE][FINANCE_VIEW] = '财务单查看';
$PERMISSIONS[FINANCE][FINANCE_EDIT] = '财务单管理(状态更改)';
$PERMISSIONS[FINANCE][FINANCE_PURCHASE_REVIEW] = '财务审核采购单';

$P_GROUP[FINANCE] = '财务管理';

// 仓储管理
define('STOCK', 7);
define('STOCK_IN_VIEW', 0);
define('STOCK_IN_EDIT', 1);
define('STOCK_PICKUP_VIEW', 2);
define('STOCK_PICKUP_EDIT', 3);
define('STOCK_SHIPPING_VIEW', 4);
define('STOCK_SHIPPING_START', 5);
define('STOCK_SHIPPING_COMPLETE', 6);
define('STOCK_VIEW', 7);


$PERMISSIONS[STOCK][STOCK_VIEW] = '库存查看';
$PERMISSIONS[STOCK][STOCK_IN_VIEW] = '入仓记录查看';
$PERMISSIONS[STOCK][STOCK_IN_EDIT] = '入仓记录管理(新增/删除)';
$PERMISSIONS[STOCK][STOCK_PICKUP_VIEW] = '分拣工单查看';
$PERMISSIONS[STOCK][STOCK_PICKUP_EDIT] = '分拣工单管理(生成/完成)';
$PERMISSIONS[STOCK][STOCK_SHIPPING_VIEW] = '运输单查看';
$PERMISSIONS[STOCK][STOCK_SHIPPING_START] = '运输单开始';
$PERMISSIONS[STOCK][STOCK_SHIPPING_COMPLETE] = '运输单完成';

$P_GROUP[STOCK] = '仓储管理';


// 配送管理
define('DISPATCH', 8);
define('DISPATCH_LIST_VIEW', 0);
define('DISPATCH_LIST_VIEW_STORE', 2);
define('DISPATCH_LIST_EDIT', 1);

//TODO 本门店订单查看权
$PERMISSIONS[DISPATCH][DISPATCH_LIST_VIEW] = '配送任务查看(全部)';
$PERMISSIONS[DISPATCH][DISPATCH_LIST_VIEW_STORE] = '配送任务查看(本门店)';
$PERMISSIONS[DISPATCH][DISPATCH_LIST_EDIT] = '配送任务管理(完成/配送失败)';

$P_GROUP[DISPATCH] = '配送管理';

// 供应商管理
define('SUPPLIER', 9);
define('SUPPLIER_VIEW', 0);
define('SUPPLIER_EDIT', 1);

$PERMISSIONS[SUPPLIER][SUPPLIER_VIEW] = '供应商查看';
$PERMISSIONS[SUPPLIER][SUPPLIER_EDIT] = '供应商管理(新增/修改/删除)';

$P_GROUP[SUPPLIER] = '供应商管理';

// 退货管理
define('REFUND', 11);
define('REFUND_ADD', 0);
define('REFUND_REVIEW', 1);
define('REFUND_FINANCE_REVIEW', 2);

$PERMISSIONS[REFUND][REFUND_ADD] = '新增退货记录';
$PERMISSIONS[REFUND][REFUND_REVIEW] = '退货记录审核';
$PERMISSIONS[REFUND][REFUND_FINANCE_REVIEW] = '退货记录财务打款';

$P_GROUP[REFUND] = '退货管理';


// 会员管理
define('USER', 10);
define('USER_VIEW', 0);
define('USER_EDIT', 1);
define('USER_RESIDENT_AREA', 2);
define('USER_RESIDENT_COMMUNITY', 3);
define('USER_RESIDENT_BUILDING', 4);
define('USER_RESIDENT_INFO', 5);
define('USER_STORE_INFO', 6);
define('USER_STORE_INFO_EDIT', 7);

$PERMISSIONS[USER][USER_VIEW] = '会员查看';
$PERMISSIONS[USER][USER_EDIT] = '会员管理(修改/删除)';
$PERMISSIONS[USER][USER_RESIDENT_AREA] = '地区码管理';
$PERMISSIONS[USER][USER_RESIDENT_COMMUNITY] = '小区信息管理';
$PERMISSIONS[USER][USER_RESIDENT_BUILDING] = '住宅楼管理';
$PERMISSIONS[USER][USER_RESIDENT_INFO] = '会员住址信息';
$PERMISSIONS[USER][USER_STORE_INFO] = '门店信息';
$PERMISSIONS[USER][USER_STORE_INFO_EDIT] = '门店信息管理(增加/修改/删除)';

$P_GROUP[USER] = '会员管理';

?>